
spring:
  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:13306/test
#    username: admin
#    password: '0000'

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:11306/gamdb2
#    url: jdbc:mysql://gam-mysql:3306/gamdb2
    username: root
    password: '0000'

  sql:
    init:
      mode: always
      encoding: utf-8
  #테이블 생성 후에 data.sql 실행
  #defer-datasource-initialization: true

mybatis:
#  configuration:
#    multiple-result-sets-enabled: false
#    map-underscore-to-camel-case: true
#    call-setters-on-nulls: true
#    jdbc-type-for-null: varchar
#    default-fetch-size: 500
  mapper-locations: classpath:mappers/*.xml
  #type-aliases-package: com.example.demo.domain
  configuration:
    map-underscore-to-camel-case: true
